CREATE TABLE tbl_StudentInfo

(
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	FIRST_NAME VARCHAR (15),
	LAST_NAME VARCHAR (15),
	GENDER VARCHAR (15),
	HOME_ADDRESS VARCHAR (100),
	USERNAME VARCHAR (15),
	PWORD VARCHAR (15),
)